templates:
    -
        path:    "NSCmsBundle:Pages:page.html.twig"
        title:   "Шаблон для всех страниц"
        default: true
        areas:
            -
                name: header
                title: "Верхняя панель"
                fixed: true
            -
                name: left
                title: "Левая панель"
            -
                name: content
                title: "Контентная область"
