templates:
    -
        path:    "NSCmsBundle:Pages:page.html.twig"
        title:   "Шаблон для всех страниц"
        default: true
        areas:
            -
                name: header
                title: "Верхняя панель"
                fixed: true
            -
                name: slider
                title: "Панель заголовка страницы"
            -
                name: catalog_menu
                title: "Меню категорий из каталога"
                fixed: true
            -
                name: content
                title: "Контентная область"
            -
                name: copyright
                title: "Текст копирайта"
                fixed: true
            -
                name: footer_menu
                title: "Меню в подвале"
                fixed: true
