blocks:
    -
        name: MGFrontBundle:Blocks:sliderBlock
        title: Слайдер с изображениями
    -
        name: MGFrontBundle:Blocks:cartBlock
        title: Корзина посетителя
    -
        name: MGFrontBundle:Blocks:checkoutBlock
        title: Блок оформления заказа