mg_product_add:
    path: /cartorder/products
    methods: [POST]
    defaults:
        _controller: MGFrontBundle:Cart:addProduct

mg_product_delete:
    path: /cartorder/products/{id}
    methods: [DELETE]
    defaults:
        _controller: MGFrontBundle:Cart:deleteProduct
    requirements:
        id: \d+

mg_product_edit:
    path: /cartorder/products/{id}
    methods: [PUT]
    defaults:
        _controller: MGFrontBundle:Cart:editProduct
    requirements:
        id: \d+

mg_product_count:
    path: /cartorder/count
    methods: [GET]
    defaults:
        _controller: MGFrontBundle:Cart:productCount