parameters:
    mg_front.catalog.item_settings_type.class: Mosgurman\FrontBundle\Catalog\ItemSettingsType

services:
    mg_front.catalog.item_settings_type:
        class: %mg_front.catalog.item_settings_type.class%
        tags:
            - { name: 'form.type', alias: 'mg_front_catalog_item_settings_type' }
